default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, jquery.mobile-1.0b2.min.css, smartphone.css, jquery-ui.css]

  javascripts:    [jquery-1.6.1.min.js, jquery.my-config.js, jquery.mobile-1.0b2.min.js, smart.js, jquery-ui.min.js]

  has_layout:     true
  layout:         layout
